name: windows10 - Manual workflow for automated tests on windows10

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Test suites'
        required: false
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14.17.0
      - name: Setup
        run: npm install
      - name: Test
        shell: bash
        run: node prepareConfig.js && ./node_modules/.bin/wdio ./wdio-github.conf.js
      - name: Screenshot handling
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: wdio-error-screenshots
          path: errorScreenshots